In [ ]:
import pandas as pd
import numpy as np
from PATHS import DATA_FOLDER
from data_prep import merge_open_close, assign_candle_id
from info_extraction import calc_profit

In [ ]:
# J = jump trailing
# S = simple trailing
# N = adt-atr filter NOT used
# L,G = adt-atr filter used and atr <, > parameter amount


#open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/open_trades_test.csv',sep=';')
#close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/closed_trades_test.csv',sep=';')
#S_N_merge_df = merge_open_close(open_df,close_df)

#open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/ADX_ATR_FILTER/ATR_FILTER_GREATERTHAN_VALUE/open_trades_test.csv',sep=';')
#close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/ADX_ATR_FILTER/ATR_FILTER_GREATERTHAN_VALUE/closed_trades_test.csv',sep=';')
#S_G_merge_df = merge_open_close(open_df,close_df)

#open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/ADX_ATR_FILTER/ATR_FILTER_LESSTHAN_VALUE/open_trades_test.csv',sep=';')
#close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/simple_trailing/ADX_ATR_FILTER/ATR_FILTER_LESSTHAN_VALUE/closed_trades_test.csv',sep=';')
#S_L_merge_df = merge_open_close(open_df,close_df)

#open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/open_trades_test.csv',sep=';')
#close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/closed_trades_test.csv',sep=';')
#J_N_merge_df = merge_open_close(open_df,close_df)

#open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/ADX_ATR_FILTER/ATR_FILTER_GREATERTHAN_VALUE/open_trades_test.csv',sep=';')
#close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/ADX_ATR_FILTER/ATR_FILTER_GREATERTHAN_VALUE/closed_trades_test.csv',sep=';')
#J_G_merge_df = merge_open_close(open_df,close_df)

open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/ADX_ATR_FILTER/ATR_FILTER_LESSTHAN_VALUE/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/ADX_ATR_FILTER/ATR_FILTER_LESSTHAN_VALUE/closed_trades_test.csv',sep=';')
base_merge_df = merge_open_close(open_df,close_df)

#open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/FILTER/Consolidation/open_trades_test.csv',sep=';')
#close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/FILTER/Consolidation/closed_trades_test.csv',sep=';')
#consolidation_merge = merge_open_close(open_df,close_df)

open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/FILTER/UpperWick/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/FILTER/UpperWick/closed_trades_test.csv',sep=';')
upperwick_merge = merge_open_close(open_df,close_df)

open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/FILTER/temp/UpperWick/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/FILTER/temp/UpperWick/closed_trades_test.csv',sep=';')
upperwick_merge_2 = merge_open_close(open_df,close_df)

open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/FILTER/temp/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/FILTER/temp/closed_trades_test.csv',sep=';')
temp_merge = merge_open_close(open_df,close_df)

df_dict = {
    #'SimpleTrailing_NoFilter_None':[S_N_merge_df],
    #'SimpleTrailing_Filter_Greater':[S_G_merge_df],
    #'SimpleTrailing_Filter_Less':[S_L_merge_df],
    #'JumpTrailing_NoFilter_None':[J_N_merge_df],
    #'JumpTrailing_Filter_Greater':[J_G_merge_df],
    'Base':[base_merge_df],
    'UpperWick':[upperwick_merge],
    'UpperWick2':[upperwick_merge_2],
    #'Consolidation':[consolidation_merge],
    'Temp':[temp_merge]
    }

for key in df_dict:
    profit_df = calc_profit(df_dict[key][0],len(df_dict[key][0]))
    profit_df['Profit_With_Drawdown'] = profit_df['Profit'] * (30 / profit_df['Max_Drawdown_Pct'])
    df_dict[key].append(profit_df)

In [ ]:
df_dict['JumpTrailing_Filter_Less'][1].sort_values(by='Profit_With_Drawdown',ascending=False).head(15)

In [130]:
data_df = df_dict['Base'][0]
data_df = data_df[data_df["Test_ID"]=='0.015_1.0_0.020_4.0']

In [134]:
# 4.0
data_df[['Ticket','OpenTime','CloseTime','Profit','OpenPrice','ClosePrice']].sort_values(by='Profit',ascending=False).head(25)

       Ticket             OpenTime  ... OpenPrice  ClosePrice
26497     129  2025.07.09 07:39:18  ...    2644.0      3641.3
26418      50  2024.11.06 05:19:29  ...    2526.6      3238.2
26478     110  2025.04.22 16:44:20  ...    1666.4      2353.3
26376       8  2024.02.14 10:55:37  ...    2699.7      3261.8
26388      20  2024.05.20 21:21:59  ...    3192.1      3685.3
26512     144  2025.09.26 14:36:47  ...    3958.1      4437.7
26431      63  2025.01.13 17:36:40  ...    2963.4      3284.5
26503     135  2025.08.09 07:05:52  ...    4139.9      4454.3
26505     137  2025.08.22 15:42:17  ...    4311.2      4606.4
26515     147  2025.10.11 23:24:01  ...    3729.6      3993.9
26423      55  2024.12.03 17:42:09  ...    3556.0      3807.6
26565     197  2026.04.07 19:36:58  ...    2114.8      2295.3
26548     180  2026.02.24 17:42:00  ...    1832.9      1997.2
26378      10  2024.03.06 06:54:32  ...    3632.4      3799.0
26484     116  2025.05.19 09:09:30  ...    2387.4      2538.3
26373       5  2024.01.10 15:12:58  ...    2390.0      2523.9
26417      49  2024.10.26 01:31:48  ...    2416.8      2526.9
26422      54  2024.11.21 15:08:54  ...    3193.1      3289.4
26527     159  2025.12.02 18:04:18  ...    2938.1      3004.0
26489     121  2025.06.09 23:11:29  ...    2627.3      2667.1
26553     185  2026.02.28 18:28:01  ...    1901.2      1933.1
26414      46  2024.09.20 05:59:01  ...    2511.3      2526.7
26566      -1                  NaN  ...       NaN        -1.0
26471     103  2025.04.11 03:33:30  ...    1547.3      1547.2
26472     104  2025.04.12 10:08:52  ...    1601.0      1600.8

[25 rows x 6 columns]

In [129]:
data_df[['Ticket','OpenTime','CloseTime','Profit','OpenPrice','ClosePrice']].sort_values(by='Profit',ascending=False).head(25)

       Ticket             OpenTime  ... OpenPrice  ClosePrice
13307     175  2025.09.26 14:36:47  ...    3958.1      4597.9
13156      24  2024.05.20 21:21:59  ...    3192.1      3708.1
13264     132  2025.05.08 05:44:47  ...    1890.4      2410.7
13298     166  2025.08.22 15:42:17  ...    4311.2      4707.5
13287     155  2025.07.16 01:08:10  ...    3138.3      3547.1
13210      78  2025.01.13 17:36:40  ...    2963.4      3352.0
13310     178  2025.10.11 23:24:01  ...    3729.6      4069.8
13286     154  2025.07.09 07:39:18  ...    2644.0      2929.3
13201      69  2024.12.03 17:42:09  ...    3556.0      3814.2
13191      59  2024.11.06 05:19:29  ...    2526.6      2777.3
13296     164  2025.08.12 14:32:31  ...    4367.8      4612.8
13346     214  2026.02.24 17:42:00  ...    1832.9      2069.9
13137       5  2024.01.10 15:12:58  ...    2390.0      2592.2
13190      58  2024.10.26 01:31:48  ...    2416.8      2623.6
13202      70  2024.12.06 01:29:37  ...    3744.0      3942.5
13324     192  2025.12.02 18:04:18  ...    2938.1      3122.0
13146      14  2024.03.11 02:54:10  ...    3793.6      3937.7
13277     145  2025.06.09 23:11:29  ...    2627.3      2772.0
13145      13  2024.03.06 06:54:32  ...    3632.4      3753.6
13270     138  2025.05.19 09:09:30  ...    2387.4      2489.2
13257     125  2025.04.22 16:44:20  ...    1666.4      1764.3
13268     136  2025.05.13 14:42:37  ...    2539.3      2633.9
13351     219  2026.02.28 18:28:01  ...    1901.2      1974.9
13369     237  2026.04.07 19:36:58  ...    2114.8      2187.4
13213      81  2025.01.19 16:56:52  ...    3240.6      3310.8

[25 rows x 6 columns]

In [141]:
#df= df_dict['Base'][1]
#df[df['Test_ID'] == '0.020_1.0_0.010_3.0'].sort_values(by='Profit_With_Drawdown',ascending=False).head(15)
#df.sort_values(by='Profit_With_Drawdown',ascending=False).head(15)
filter_df = df_dict['Base'][1]
prefix = '0.015'
filtered_df = filter_df[filter_df["Test_ID"].str.startswith(prefix)]
filter_df.sort_values(by='Profit_With_Drawdown',ascending=False).head(20)

                 Test_ID  Type  ...  Losing_Count  Profit_With_Drawdown
66   0.020_1.0_0.025_3.0  Long  ...            60          17387.862796
64   0.020_1.0_0.025_1.0  Long  ...            46          17287.619524
83   0.025_1.0_0.015_4.0  Long  ...            27          16460.331455
63   0.020_1.0_0.020_4.0  Long  ...            62          16160.769324
86   0.025_1.0_0.020_3.0  Long  ...            24          15653.198006
54   0.020_1.0_0.010_3.0  Long  ...            76          13959.950326
62   0.020_1.0_0.020_3.0  Long  ...            65          13328.140429
90   0.025_1.0_0.025_3.0  Long  ...            24          12758.820092
55   0.020_1.0_0.010_4.0  Long  ...            77          12493.204307
68   0.020_1.0_0.030_1.0  Long  ...            43          12429.478680
87   0.025_1.0_0.020_4.0  Long  ...            25          12254.806588
65   0.020_1.0_0.025_2.0  Long  ...            59          12188.523641
67   0.020_1.0_0.025_4.0  Long  ...            62          12046.689277
106  0.030_1.0_0.015_3.0  Long  ...            14          12040.598062
107  0.030_1.0_0.015_4.0  Long  ...            15          11955.433923
61   0.020_1.0_0.020_2.0  Long  ...            61          11755.623391
85   0.025_1.0_0.020_2.0  Long  ...            24          11451.293286
69   0.020_1.0_0.030_2.0  Long  ...            58          11280.516070
93   0.025_1.0_0.030_2.0  Long  ...            22          10800.040675
59   0.020_1.0_0.015_4.0  Long  ...            73          10293.373562

[20 rows x 11 columns]

In [ ]:
# 0.010_1.0_0.020_2.0 with consolidation lookback:15 Maxpercent:4

In [139]:
filter_df = df_dict['Temp'][1]
filter_df = filter_df[filter_df['Trade_Count'] > 20]
prefix = '0.005_1.0_0.015_2.0_15.0'
filtered_df = filter_df[filter_df["Test_ID"].str.startswith(prefix)]
filter_df.sort_values(by='Profit_With_Drawdown',ascending=False)

                         Test_ID  Type  ...  Losing_Count  Profit_With_Drawdown
45  0.015_1.0_0.020_4.0_25.0_3.0  Long  ...            94           4046.544217
42  0.015_1.0_0.020_4.0_20.0_3.0  Long  ...           116           3633.256091
40  0.015_1.0_0.020_4.0_15.0_4.0  Long  ...           157           3105.095816
37  0.015_1.0_0.020_4.0_10.0_4.0  Long  ...           162           2241.980710
38  0.015_1.0_0.020_4.0_10.0_5.0  Long  ...           170           2139.149484
44  0.015_1.0_0.020_4.0_20.0_5.0  Long  ...           167           1623.493381
39  0.015_1.0_0.020_4.0_15.0_3.0  Long  ...           134           1482.119710
41  0.015_1.0_0.020_4.0_15.0_5.0  Long  ...           168           1481.570890
28  0.015_1.0_0.020_3.0_15.0_4.0  Long  ...           170           1237.970169
47  0.015_1.0_0.020_4.0_25.0_5.0  Long  ...           161           1132.542218
26  0.015_1.0_0.020_3.0_10.0_5.0  Long  ...           184            831.008160
30  0.015_1.0_0.020_3.0_20.0_3.0  Long  ...           121            807.547200
16  0.015_1.0_0.020_2.0_15.0_4.0  Long  ...           174            675.129732
18  0.015_1.0_0.020_2.0_20.0_3.0  Long  ...           120            620.312858
43  0.015_1.0_0.020_4.0_20.0_4.0  Long  ...           153            508.357993
33  0.015_1.0_0.020_3.0_25.0_3.0  Long  ...            98            467.831415
25  0.015_1.0_0.020_3.0_10.0_4.0  Long  ...           176            443.852563
36  0.015_1.0_0.020_4.0_10.0_3.0  Long  ...           155            397.941797
46  0.015_1.0_0.020_4.0_25.0_4.0  Long  ...           138            333.465120
14  0.015_1.0_0.020_2.0_10.0_5.0  Long  ...           191            200.027760
15  0.015_1.0_0.020_2.0_15.0_3.0  Long  ...           144            162.117819
19  0.015_1.0_0.020_2.0_20.0_4.0  Long  ...           163             88.173443
32  0.015_1.0_0.020_3.0_20.0_5.0  Long  ...           181             12.172917
29  0.015_1.0_0.020_3.0_15.0_5.0  Long  ...           182             11.956452
27  0.015_1.0_0.020_3.0_15.0_3.0  Long  ...           144              2.653846
22  0.015_1.0_0.020_2.0_25.0_4.0  Long  ...           148              1.094736
21  0.015_1.0_0.020_2.0_25.0_3.0  Long  ...            97            -22.264346
35  0.015_1.0_0.020_3.0_25.0_5.0  Long  ...           172            -77.359874
13  0.015_1.0_0.020_2.0_10.0_4.0  Long  ...           182           -169.027222
34  0.015_1.0_0.020_3.0_25.0_4.0  Long  ...           146           -178.734131
12  0.015_1.0_0.020_2.0_10.0_3.0  Long  ...           164           -189.828626
31  0.015_1.0_0.020_3.0_20.0_4.0  Long  ...           164           -366.208681
17  0.015_1.0_0.020_2.0_15.0_5.0  Long  ...           188           -474.000813
20  0.015_1.0_0.020_2.0_20.0_5.0  Long  ...           186           -544.254594
24  0.015_1.0_0.020_3.0_10.0_3.0  Long  ...           166           -586.253984
23  0.015_1.0_0.020_2.0_25.0_5.0  Long  ...           179           -675.326799
6   0.015_1.0_0.020_1.0_20.0_3.0  Long  ...           108           -975.471268
3   0.015_1.0_0.020_1.0_15.0_3.0  Long  ...           132          -1165.199152
0   0.015_1.0_0.020_1.0_10.0_3.0  Long  ...           151          -1327.293153
7   0.015_1.0_0.020_1.0_20.0_4.0  Long  ...           151          -1415.055558
9   0.015_1.0_0.020_1.0_25.0_3.0  Long  ...            87          -1502.386343
10  0.015_1.0_0.020_1.0_25.0_4.0  Long  ...           133          -1551.511966
4   0.015_1.0_0.020_1.0_15.0_4.0  Long  ...           162          -1707.262824
1   0.015_1.0_0.020_1.0_10.0_4.0  Long  ...           170          -1986.978008
2   0.015_1.0_0.020_1.0_10.0_5.0  Long  ...           179          -2025.452744
8   0.015_1.0_0.020_1.0_20.0_5.0  Long  ...           173          -2113.404180
11  0.015_1.0_0.020_1.0_25.0_5.0  Long  ...           166          -2154.166597
5   0.015_1.0_0.020_1.0_15.0_5.0  Long  ...           177          -2155.847179

[48 rows x 11 columns]

In [110]:
filter_df = df_dict['Temp'][1]
filter_df = filter_df[filter_df['Trade_Count'] > 20]
prefix = '0.005_1.0_0.015_2.0_15.0'
filtered_df = filter_df[filter_df["Test_ID"].str.startswith(prefix)]
filter_df.sort_values(by='Profit',ascending=False).iloc[3:4]

                        Test_ID  Type  ...  Losing_Count  Profit_With_Drawdown
4  0.010_1.0_0.020_2.0_15.0_4.0  Long  ...           491          -2332.281981

[1 rows x 11 columns]