Evaluation of test runs by hand.

In [62]:
import pandas as pd
import numpy as np
from PATHS import DATA_FOLDER
from data_prep import merge_open_close, assign_candle_id
from info_extraction import calc_profit

In [63]:
open_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/open_trades_test.csv',sep=';')
close_df = pd.read_csv(DATA_FOLDER + 'M15/2024-2026/smaller_spike/jump_trailing/closed_trades_test.csv',sep=';')
base_merge_df = merge_open_close(open_df,close_df)

df_dict = {
    'Base':[base_merge_df],
    }

for key in df_dict:
    profit_df = calc_profit(df_dict[key][0],len(df_dict[key][0]))
    profit_df['Profit_With_Drawdown'] = profit_df['Profit'] * (30 / profit_df['Max_Drawdown_Pct'])
    df_dict[key].append(profit_df)

In [64]:
#df= df_dict['Base'][1]
#df[df['Test_ID'] == '0.020_1.0_0.010_3.0'].sort_values(by='Profit_With_Drawdown',ascending=False).head(15)
#df.sort_values(by='Profit_With_Drawdown',ascending=False).head(15)
filter_df = df_dict['Base'][1]
prefix = '0.020'
filtered_df = filter_df[filter_df["Test_ID"].str.startswith(prefix)]
filtered_df.sort_values(by='Winning_Profit',ascending=False).head(20)

,Test_ID,Type,Profit,Max_Drawdown,Max_Drawdown_Pct,Trade_Count,Winning_Profit,Winning_Count,Losing_Profit,Losing_Count,Profit_With_Drawdown
25,0.020_4.0_1.5,Long,401.223630,331.430000,3.154848,97,1724.984500,25,-1323.760870,72,3815.305553
26,0.020_4.0_2.0,Long,394.371235,330.190000,3.154855,97,1724.911623,22,-1330.540388,75,3750.136145
23,0.020_3.0_2.0,Long,455.376174,277.070000,2.594355,97,1619.266562,22,-1163.890388,75,5265.773465
22,0.020_3.0_1.5,Long,205.542685,287.300000,2.753854,99,1375.590000,26,-1170.047315,73,2239.145957
24,0.020_4.0_1.0,Long,-86.546949,417.420000,4.073577,100,1257.100000,29,-1343.646949,71,-637.377977
21,0.020_3.0_1.0,Long,-13.277315,393.990000,3.809246,102,1156.372685,31,-1169.650000,71,-104.566490
20,0.020_2.0_2.0,Long,-1.936949,319.546949,3.123565,101,926.790000,18,-928.726949,83,-18.603254
19,0.020_2.0_1.5,Long,-91.826949,309.146949,3.029519,102,820.003051,22,-911.830000,80,-909.322108
18,0.020_2.0_1.0,Long,-351.670000,404.160000,4.026264,102,519.280000,28,-870.950000,74,-2620.320005

In [65]:
# Order trades by time (without grouping by test_id)
df = df_dict['Base'][0]
df["OpenTime"] = pd.to_datetime(df["OpenTime"], format="%Y.%m.%d %H:%M:%S")

# sort by datetime
df = df.sort_values(by="OpenTime")

# (optional) reset index
df = df.reset_index(drop=True)

In [67]:
df[['Test_ID','Ticket','OpenTime','CloseTime']].head(20)

          Test_ID  Ticket            OpenTime            CloseTime
0   0.010_2.0_1.0       1 2024-01-03 14:02:04  2024.01.03 14:02:04
1   0.010_3.0_1.0       1 2024-01-03 14:02:04  2024.01.03 14:03:56
2   0.010_4.0_2.0       1 2024-01-03 14:02:04  2024.01.03 14:06:51
3   0.010_4.0_1.0       1 2024-01-03 14:02:04  2024.01.03 14:04:23
4   0.010_3.0_2.0       1 2024-01-03 14:02:04  2024.01.03 14:05:24
5   0.010_2.0_1.5       1 2024-01-03 14:02:04  2024.01.03 14:02:04
6   0.010_3.0_1.5       1 2024-01-03 14:02:04  2024.01.03 14:04:39
7   0.010_4.0_1.5       1 2024-01-03 14:02:04  2024.01.03 14:05:23
8   0.010_2.0_2.0       1 2024-01-03 14:02:04  2024.01.03 14:02:04
9   0.015_2.0_1.5       1 2024-01-03 14:02:14  2024.01.03 14:04:23
10  0.015_2.0_1.0       1 2024-01-03 14:02:14  2024.01.03 14:03:56
11  0.015_4.0_1.0       1 2024-01-03 14:02:14  2024.01.03 14:05:23
12  0.015_3.0_2.0       1 2024-01-03 14:02:14  2024.01.03 14:04:24
13  0.015_3.0_1.5       1 2024-01-03 14:02:14  2024.01.03 14:04:24
14  0.015_3.0_1.0       1 2024-01-03 14:02:14  2024.01.03 14:04:24
15  0.015_2.0_2.0       1 2024-01-03 14:02:14  2024.01.03 14:04:23
16  0.015_4.0_2.0       1 2024-01-03 14:02:14  2024.01.03 14:05:23
17  0.015_4.0_1.5       1 2024-01-03 14:02:14  2024.01.03 14:05:23
18  0.020_4.0_1.0       1 2024-01-03 14:02:51  2024.01.03 14:06:53
19  0.020_3.0_1.0       1 2024-01-03 14:02:51  2024.01.03 14:05:23